name: Deploy to Alwaysdata

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Deploy application files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ ftp-jojoapp.alwaysdata.net }}
          username: ${{ jojoapp }}
          password: ${{ 3108787231Jc. }}
          server-dir: www/
          protocol: ftps
          exclude: |
            **/.git*/**
            **/.github/**
